version: '3.9'
services:
  db:
    image: postgres
    container_name: localpg
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pw
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
  node:
    build: .
    image: backend:latest
    container_name: backend
    depends_on:
      - db
    ports:
      - '3000:3000'
